require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - bin/**
    - config.ru
    - config/application.rb
    - config/boot.rb
    - config/environment.rb
    - config/environments/**/*.rb
    - config/initializers/**/*.rb
    - config/puma.rb
    - config/routes.rb
    - config/spring.rb
    - db/seeds.rb
    - Gemfile
    - Rakefile
    - spec/rails_helper.rb
    - spec/spec_helper.rb    

